It doesn't work
densioli/Hangman pull request #19
Opened 2018-05-28 03:48 UTC by tokiiiiiiiin

am sory

hello fren

2018-05-28 03:54 UTC, KMamuyac reviewed
refer to LetterChecker.cpp and LetterChecker.h and then add minor adjustments.

Refer to OChecker or UChecker if you want

2018-05-28 03:54 UTC, KMamuyac commented on src/PChecker.cpp
> +	char checkMyLetter(char inputChar){char defaultLetter = inputChar;if(inputChar == 'p' || inputChar == 'P'){return 'p';}else{return defaultLetter;}}
refer to src/LetterChecker.cpp you only need minor changes in the code

2018-05-28 03:55 UTC, KMamuyac requested changes
change c:

2018-06-11 01:33 UTC, tokiiiiiiiin reviewed
okay na siya pls accep

2018-06-11 01:34 UTC, tokiiiiiiiin commented
pls aksep

2018-06-11 01:51 UTC, KMamuyac approved these changes
Nice job

2018-06-11 01:56 UTC, KMamuyac commented
boss, squash and merge boss

2018-06-11 02:38 UTC, merged