N checking
densioli/Hangman pull request #21
Opened 2018-05-28 03:48 UTC by Khobaka

codes to check if N is the input, please have mercy on me. (Q__Q )

2018-05-28 04:07 UTC, alylagayan reviewed
????? ¯\_(ツ)_/¯ ???????

?????you might wanna work on the inheritance there????

to put it simply, it didn't print. :(

HELP

2018-06-04 02:23 UTC, Khobaka commented
Already updated it, please re check! >W<)

2018-06-04 03:32 UTC, alylagayan commented on include/NChecker.h
>  };
Remove protected

2018-06-04 03:33 UTC, alylagayan commented on include/NChecker.h
> +	virtual char checkMyLetter(char inputChar);
Remove 'virtual' and add override after the end parenthesis

2018-06-04 03:39 UTC, alylagayan commented on src/NChecker.cpp
switch return values so that it returns 'n' if true and '*' (which was declared already in defaultLetter) in the else stmt

2018-06-04 03:40 UTC, alylagayan commented on include/NChecker.h
>  };
+protected:
+	char defaultLetter;

remove from code

2018-06-04 03:46 UTC, alylagayan requested changes
Check the comments!!

2018-06-04 03:55 UTC, alylagayan approved these changes

2018-06-11 01:13 UTC, merged