Merged ACheckerVillagantol to Development
densioli/Hangman pull request #22
Opened 2018-05-28 03:48 UTC by TedskieBear

Submitted activity.

2018-06-04 01:45 UTC, amstelventanilla requested changes
review your code

2018-06-04 01:45 UTC, amstelventanilla commented on src/AChecker.cpp
> +        std::cout << "YAY\n";
remove unnecessary comments

2018-06-04 02:05 UTC, amstelventanilla approved these changes
good job!

2018-06-18 01:09 UTC, densioli commented
closing this since it is old and will not be used

2018-06-18 01:09 UTC, closed without merging